services:
  app:
    container_name: ${APP_HOST:-latex}
    build: .
    volumes:
      - ./as_is/:/home/app/as_is/
    networks:
      - public
      
networks:
  public:
    external: true

