services:
  app:
    container_name: ${APP_HOST:-img_search}
    build: .
    volumes:
      - ./src_old/:/home/app/src_old/
    networks:
      - public
      
networks:
  public:
    external: true

